import { AccountTypes, Genders, User as UserModel } from '@prisma/client';
import { Decimal } from '@prisma/client/runtime';
export class User implements UserModel {
  currentLatitude: Decimal;
  currentLongitude: Decimal;
  location: string;
  firstName: string;
  lastName: string;
  countryId: string;
  stateId: string;
  cityId: string;
  accountType: AccountTypes;
  roleId: string;
  id: string;
  email: string;
  password: string;
  image: string;
  username: string;
  gender: Genders;
  phoneNumber: string;
  bio: string;
  provider: string;
  providerId: string;
  otpCounter: number;
  referrerId: string;
  referralCode;
  referral: UserModel;
  dateOfBirth: Date;
  phoneNumberVerifiedAt: Date;
  emailVerifiedAt: Date;
  websocketId: string;
  createdAt: Date;
  updatedAt: Date;
}
